# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-19 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKUInOrderCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('cat', models.CharField(max_length=200)),
                ('suggested', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SKUPairInOrderCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=200)),
                ('sku1', models.CharField(max_length=200)),
                ('sku2', models.CharField(max_length=200)),
                ('cat1', models.CharField(max_length=200)),
                ('cat2', models.CharField(max_length=200)),
                ('suggested1', models.BooleanField(default=False)),
                ('suggested2', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
