# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemplacedsample',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsplacedtogethersample',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
