# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-17 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='suggested',
            field=models.BooleanField(default=False),
        ),
    ]
