# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-17 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(max_length=200),
        ),
    ]
